config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users, only: :show

  get "timeline" => "static_pages#timeline"
  get 'user/timeline', to: 'users#timeline' # for timeline.json

  resources :follows, only: [:create, :destroy] 

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :posts do
  	resources :post_comments
  	resources :upvotes, only: :create
  	resources :downvotes, only: :create
  end

  root 'posts#index' 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :photo, PhotoUploader
  
  # notification
  has_many :notifications, foreign_key: :recipient_id, dependent: :destroy

  has_many :posts, -> { order(created_at: :desc) }, dependent: :destroy

  has_many :post_comments, dependent: :destroy

  acts_as_voter

  has_many :following_relationships, -> { Follow.where(active: true) }, class_name:  "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followed_relationships, -> { Follow.where(active: true) }, class_name:  "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :following_users, -> { Follow.where(active: true) }, through: :following_relationships, source: :followed
  has_many :followed_users, -> { Follow.where(active: true) }, through: :followed_relationships, source: :follower

  # follow user
  def follow(other_user)
    relationship = Follow.where(followed_id: other_user.id, follower_id: self.id ).first
    if relationship.present?
      relationship.update(active: true) 
    else
      following_relationships.create(followed_id: other_user.id)
      Notification.create(recipient: other_user, actor: self, action: 'follow', notifiable: other_user)
    end
  end

  # unfollow user
  def unfollow(other_user)
    relationship = Follow.where(followed_id: other_user.id, follower_id: self.id)
    relationship.update(active: false) if relationship.present?
    # following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following that user
  def following?(user)
    Follow.exists?(followed_id: user.id, follower_id: self.id, active: true)
    # following_relationships.exists?(followed_id: user.id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:timeline]

	def show
	  @user = User.find(params[:id])
	end

	def timeline
		@posts = Post.where(user: current_user.following_users).order("created_at DESC")
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<% if user != current_user && user_signed_in? %>
	<div class="follow-button mp-margin">
	<% if current_user.following?(user) %>
		<%= link_to "Following", follow_path(id: user.id), class: 'btn btn-success btn-lg', method: :delete, remote: true %>
	<% else %>
		<%= link_to "Follow", follows_path(id: user.id), class: 'btn btn-warning btn-lg', method: :post, remote: true %>
	<% end %>
	</div>
<% end %>
<ul class="user-stats count">
  <li id="user-posts">
    <div class="number-label"><%= "Post".pluralize(@user.posts.count) %></div>
    <div class="number-value"><%= @user.posts.count %></div>
  </li>
  <li id="user-followers">
    <div class="number-label"><%= "Follower".pluralize(@user.followed_relationships.count) %></div>
    <div class="number-value"><%= @user.followed_relationships.count %></div>
  </li>
  <li id="user-following">
    <div class="number-label"><%= "Following".pluralize(@user.following_relationships.count) %></div>
    <div class="number-value"><%= @user.following_relationships.count %></div>    
  </li>
</ul>

app/views/users/show.html.erb
<div class="prof_header">

  <div class="row text-center">

    <div class="col-sm-3">
      <% if @user.photo? %>
        <%= cl_image_tag @user.photo, :secure => true, class: 'prof_pic' %>
      <% else %>
        <%= image_tag "https://goo.gl/2wWxZy", class: 'prof_pic' %>
      <% end %>
    </div>

    <div class="col-sm-3"></div>

    <div class="col-sm-6">

      <div class="user_header">

        <div class="row">
          <div class="user_photo">
            <h1 class = "username"><%= @user.name %></h1>
          </div>

          <div class="edit_profile mp-margin">
            <%= link_to 'EDIT PROFILE', edit_user_registration_path(@user), class: 'user_edit_button btn btn-default right' if user_signed_in? && @user == current_user %>
          </div>
          <div id="follow_container_<%= @user.id %>" class="text-center">
            <%= render partial: 'follow', locals: {user: @user} %>
          </div>
        </div>  
      </div>

    </div>

  </div>

</div>
<hr>

<div class="prof_post_box">
    <div id="all-user-posts"></div>
</div>

<script type="text/javascript">
  $(function(){
    let userData = {};
    let user_id = <%= @user.id %>;
    $.ajax({
      url: '/users/' + user_id + '.json',
      type: 'GET'
    })
    .done(function(data) {
      userData = data;
      displayPosts(data);
    });
    function displayPosts(data) {
      let container = $("#all-user-posts");
      let htmlString = "";
      container.empty();
      if (data["posts"].length == 0) {
        htmlString = `<div class="alert alert-danger text-center" role="alert">This user has no posts yet!</div>`
      } else {
        data["posts"].forEach(function(data) {
          htmlString += `<div class="col-xs-4">
                          <a href="/posts/${data["post"]["id"]}">
                            <img src=${data["post"]["photo"]["url"]} class="prof_show">
                          </a>
                        </div>`
        });
      }
      container.append(htmlString);
    }
    $('#user-posts').on('click', function(e){
      $('#all-user-posts').empty();
      displayPosts(userData);
    });
    $('#user-following').on('click', function(e){
      $('#all-user-posts').empty();
      getFollowing();
    });
    $('#user-followers').on('click', function(e){
      $('#all-user-posts').empty();
      getFollowers();
    });
    function getFollowing(){
      let htmlString = "";
      if(userData.following_relationships == ""){
        htmlString += `<div class="alert alert-info text-center"><p>This user has not followed any users yet.</p></div>`;
      } else {
          userData.following_relationships.forEach(function(userInfo){
            htmlString += `
                          <div class="row">
                            <div class="col-xs-10 col-sm-8 col-sm-offset-2 col-xs-offset-1">
                              <div class="panel panel-success">
                                <div class="panel-body">
                                  <a href="/users/${userInfo["user"]["id"]}">
                                    <div class="row follow_pic_small">
                                      <img class="col-xs-4" src=${userInfo["user"]["photo"]["url"] == null ? "https://goo.gl/2wWxZy" : userInfo["user"]["photo"]["url"]}><p class="col-xs-4">${userInfo["user"]["name"]}</p>
                                    </div>
                                  </a>
                                </div>
                              </div>
                            </div>
                          </div>`;
        });
      }
      $('#all-user-posts').append(htmlString);
    }
    function getFollowers(){
      let htmlString = "";
      if(userData.followed_relationships == ""){
        htmlString += `<div class="alert alert-info text-center"><p>This user has no followers yet.</p></div>`;
      }
      else{
        userData.followed_relationships.forEach(function(userInfo){
          htmlString += `
                        <div class="row">
                            <div class="col-xs-10 col-sm-8 col-sm-offset-2 col-xs-offset-1">
                              <div class="panel panel-success">
                                <div class="panel-body">
                                  <a href="/users/${userInfo["user"]["id"]}">
                                    <div class="row follow_pic_small">
                                      <img class="col-xs-4" src=${userInfo["user"]["photo"]["url"] == null ? "https://goo.gl/2wWxZy" : userInfo["user"]["photo"]["url"]}><p class="col-xs-4">${userInfo["user"]["name"]}</p>
                                    </div>
                                  </a>
                                </div>
                              </div>
                            </div>
                          </div>`;
        });
      }
      $('#all-user-posts').append(htmlString);
    }
  });
</script>