config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users, only: :show

  get "timeline" => "static_pages#timeline"
  get 'user/timeline', to: 'users#timeline' # for timeline.json

  resources :follows, only: [:create, :destroy] 

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :posts do
  	resources :post_comments
  	resources :upvotes, only: :create
  	resources :downvotes, only: :create
  end

  root 'posts#index' 
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user

	belongs_to :post
	
	delegate :name, to: :user, prefix: true

	validates :text, :user_id, :post_id, presence: true
end

app/models/follow.rb
class Follow < ApplicationRecord
	validates :follower, :followed, presence: true
	validates :followed_id, uniqueness: {scope: :follower_id}
	
	belongs_to :follower, class_name: "User"
	belongs_to :followed, class_name: "User"
end

app/models/notification.rb
class Notification < ApplicationRecord
	belongs_to :recipient, class_name: "User"
    belongs_to :actor, class_name: "User"
    belongs_to :notifiable, polymorphic: true

    scope :unread, ->{ where read_at: nil }
    scope :recent, ->{ order(created_at: :desc).limit(5) }

    # 15 Notification per page
    self.per_page = 15
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	self.per_page = 3

	belongs_to :user
	
	has_many :post_comments, -> { order(created_at: :asc) }, dependent: :destroy

	has_many :users, through: :post_comments

	validates :description, :user_id, presence: true

	delegate :photo, :name, to: :user, prefix: true

	acts_as_votable

	has_many :notifications, as: :notifiable, dependent: :destroy
end

app/models/post_comment.rb
class PostComment < ApplicationRecord
	belongs_to :user

	belongs_to :post
	
	delegate :name, to: :user, prefix: true

	validates :text, :user_id, :post_id, presence: true

	has_many :notifications, as: :notifiable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :photo, PhotoUploader
  
  # notification
  has_many :notifications, foreign_key: :recipient_id, dependent: :destroy

  has_many :posts, -> { order(created_at: :desc) }, dependent: :destroy

  has_many :post_comments, dependent: :destroy

  acts_as_voter

  has_many :following_relationships, -> { Follow.where(active: true) }, class_name:  "Follow", foreign_key: "follower_id", dependent: :destroy
  has_many :followed_relationships, -> { Follow.where(active: true) }, class_name:  "Follow", foreign_key: "followed_id", dependent: :destroy

  has_many :following_users, -> { Follow.where(active: true) }, through: :following_relationships, source: :followed
  has_many :followed_users, -> { Follow.where(active: true) }, through: :followed_relationships, source: :follower

  # follow user
  def follow(other_user)
    relationship = Follow.where(followed_id: other_user.id, follower_id: self.id ).first
    if relationship.present?
      relationship.update(active: true) 
    else
      following_relationships.create(followed_id: other_user.id)
      Notification.create(recipient: other_user, actor: self, action: 'follow', notifiable: other_user)
    end
  end

  # unfollow user
  def unfollow(other_user)
    relationship = Follow.where(followed_id: other_user.id, follower_id: self.id)
    relationship.update(active: false) if relationship.present?
    # following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # Returns true if the current user is following that user
  def following?(user)
    Follow.exists?(followed_id: user.id, follower_id: self.id, active: true)
    # following_relationships.exists?(followed_id: user.id)
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController
	before_action :authenticate_user!
	before_action :check_user

	def create
		current_user.follow(@user)
		
		respond_to do |format|
            format.html { redirect_to user_path(@user.id) }
            format.js {}
        end
	end

	def destroy
	  current_user.unfollow(@user)

	  respond_to do |format|
            format.html { redirect_to user_path(@user.id) }
            format.js {}
      end
	end

	private

	def check_user
		@user = User.find(params[:id])
		if @user == current_user
			flash[:alert] = "Opps! You are trying to follow yourself!"
			render :js => "window.location.reload()"
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :is_owner?, only: [:edit, :update, :destroy]

	def index
	  @posts = Post.order('created_at DESC').paginate(page: params[:page]).includes(:user, post_comments: :user)
	  respond_to do |format|
	      format.html
	      format.js
	    end
	end

	def new
	  @post = Post.new
	end

	def create
	  @post = current_user.posts.create(post_params)
	  if @post.valid?
	  	flash[:success] = "Your post has been successfully posted!"
	    redirect_to root_path
	  else
	  	flash[:alert] = "#{@post.errors.full_messages.join(',')}"
	    render :new, status: :unprocessable_entity
	  end
	end

	def edit
	  @post = Post.find(params[:id])
	end

	def update
	  @post = Post.find(params[:id])
	  @post.update(post_params)
	  if @post.valid?
	  	flash[:success] = "Your post has been successfully updated!"
	    redirect_to root_path
	  else
	  	flash[:alert] = "Woops! Looks like there has been an error!"
	    render :edit, status: :unprocessable_entity
	  end
	end

	def show
	  @post = Post.find(params[:id])
	end

	def destroy
	  @post = Post.find(params[:id])
	  @post.destroy
	  flash[:success] = "The post was successfully deleted!"
	  redirect_to root_path
	end
	
	private

	def is_owner?
	  redirect_to root_path if Post.find(params[:id]).user != current_user
	end

	def post_params
	  params.require(:post).permit(:user_id, :photo, :description)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:timeline]

	def show
	  @user = User.find(params[:id])
	end

	def timeline
		@posts = Post.where(user: current_user.following_users).order("created_at DESC")
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/downvotes_helper.rb
module DownvotesHelper
end

app/helpers/follows_helper.rb
module FollowsHelper
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/upvotes_helper.rb
module UpvotesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_footer.html.erb
<footer>
	<div class="footer text-center container">
		&copy; <a href="https://poudelmadhav.com.np">Madhav Paudel</a> <%= Date.today.year %>. All Rights Reserved.
	</div>
</footer>

app/views/shared/_nav.html.erb
<div class="navbar navbar-default header" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      </button>
      <span class="pull-left head-size logo">
        <%= link_to root_path do %>
          <i class="fa fa-instagram" aria-hidden="true"></i> | 
        <% end %>
        <strong><span class="brand"><%= link_to 'Instapost', root_path %></span></strong>
      </span>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to ' New Post', new_post_path, class: 'fa fa-pencil-square-o' %></li>
          <li class="dropdown nav-notify" data-behavior="notifications" data-notifications='<%= render template: "notifications/index", formats: [:json] %>'>
            <a href="#" class="dropdown-toggle" data-behavior="notifications-link" data-toggle="dropdown"><span class="glyphicon glyphicon-bell"></span><sup><span class="badge" data-behavior="unread-count"></span></sup><b class="caret"></b></a>
            <ul class="dropdown-menu" data-behavior="notification-items">
              <!-- notification-items -->
            </ul>
          </li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <% if current_user.photo? %>
                <span class="header_pic_small">
                  <%= cl_image_tag current_user.photo, :secure => true, alt: current_user.name.split[0], title: current_user.name %>
                </span>
              <% else %>
                <span class="header_pic_small">
                  <%= image_tag "https://goo.gl/2wWxZy" %>
                </span>
              <% end %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li class="dropdown-header"><%= current_user.name %></li>
              <li><%= link_to 'Admin Area', admin_root_path if current_user.admin? %></li>
              <li><%= link_to "Timeline", timeline_path %></li>
              <li><%= link_to 'Profile', user_path(current_user.id) %></li>
              <li class="divider"></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <% end %>
      </ul>
    </div>
  </div>     
</div>