config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  devise_for :users

  resources :users, only: :show

  get "timeline" => "static_pages#timeline"
  get 'user/timeline', to: 'users#timeline' # for timeline.json

  resources :follows, only: [:create, :destroy] 

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :posts do
  	resources :post_comments
  	resources :upvotes, only: :create
  	resources :downvotes, only: :create
  end

  root 'posts#index' 
end

app/models/post.rb
class Post < ApplicationRecord
	mount_uploader :photo, PhotoUploader

	self.per_page = 3

	belongs_to :user
	
	has_many :post_comments, -> { order(created_at: :asc) }, dependent: :destroy

	has_many :users, through: :post_comments

	validates :description, :user_id, presence: true

	delegate :photo, :name, to: :user, prefix: true

	acts_as_votable

	has_many :notifications, as: :notifiable, dependent: :destroy
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!, only: [:new, :create]
	before_action :is_owner?, only: [:edit, :update, :destroy]

	def index
	  @posts = Post.order('created_at DESC').paginate(page: params[:page]).includes(:user, post_comments: :user)
	  respond_to do |format|
	      format.html
	      format.js
	    end
	end

	def new
	  @post = Post.new
	end

	def create
	  @post = current_user.posts.create(post_params)
	  if @post.valid?
	  	flash[:success] = "Your post has been successfully posted!"
	    redirect_to root_path
	  else
	  	flash[:alert] = "#{@post.errors.full_messages.join(',')}"
	    render :new, status: :unprocessable_entity
	  end
	end

	def edit
	  @post = Post.find(params[:id])
	end

	def update
	  @post = Post.find(params[:id])
	  @post.update(post_params)
	  if @post.valid?
	  	flash[:success] = "Your post has been successfully updated!"
	    redirect_to root_path
	  else
	  	flash[:alert] = "Woops! Looks like there has been an error!"
	    render :edit, status: :unprocessable_entity
	  end
	end

	def show
	  @post = Post.find(params[:id])
	end

	def destroy
	  @post = Post.find(params[:id])
	  @post.destroy
	  flash[:success] = "The post was successfully deleted!"
	  redirect_to root_path
	end
	
	private

	def is_owner?
	  redirect_to root_path if Post.find(params[:id]).user != current_user
	end

	def post_params
	  params.require(:post).permit(:user_id, :photo, :description)
	end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_likes.html.erb
<% if user_signed_in? %>
  <span class="post_like">
    <% if current_user.voted_up_on? post %>
      <%= link_to '<i class="fa fa-heart heart" aria-hidden="true"></i>'.html_safe, post_downvotes_path(post.id), title: 'Dislike', method: :post, remote: true %> 
    <% else %>
      <%= link_to '<i class="fa fa-heart-o anti-heart" aria-hidden="true"></i>'.html_safe, post_upvotes_path(post.id), title: 'Like',method: :post, remote: true %>
    <% end %>

    <strong><%= pluralize post.get_likes.size, "like" %></strong>
  </span>
<% else %>
  <span class="post_like">
    <i class="fa fa-heart-o" aria-hidden="true"></i>  <strong><%= pluralize post.get_likes.size, "like" %></strong>
  </span>
<% end %><br>

app/views/posts/_post.html.erb
<div class="post_box">

  <div class="post_header">
    <%= link_to (cl_image_tag post.user_photo, :secure => true), user_path(post.user_id), class: 'prof_pic_small' %>
    <%= link_to post.user_name, user_path(post.user_id) %>
    <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, post.created_at) %> ago</span>
  </div>
  <%= cl_image_tag post.photo, :secure => true, class: 'photo' %>

  <div class="post_body row">
    <!-- Like button and number of likes started -->
    <span id="likes_container_<%= post.id %>">
      <%= render partial: 'likes', locals: {post: post} %>
    </span>
    <!-- like Button and number of likes ended -->

    <%= post.description %>
    <br><br>
    <%= link_to 'View Post', post_path(post.id), class: 'btn btn-info btn-sm' %>
    <% if post.user == current_user %>
      <%= link_to 'Edit Post', edit_post_path(post.id), class: 'btn btn-warning btn-sm' %>
      <%= link_to 'Delete Post', post_path(post.id), method: :delete, class: 'btn btn-danger btn-sm', data: { title: "Are you sure?", confirm: "Your post will be deleted. This cannot be undone." } %>
    <% end %>
  </div>
  <!-- comment section -->
  <span id="post_comments_container_<%= post.id %>">
    <%= render partial: 'post_comments', locals: {post: post} %>
  </span>
</div>

app/views/posts/_post_comments.html.erb
<div class="post_comments row">
<% post.post_comments.each do |comment| %>
  <span id="comment_<%= comment.id %>">
    <%= link_to comment.user_name, user_path(comment.user_id) %> <%= comment.text %>
    <%if comment.user == current_user %>
      <%= link_to '', post_post_comment_path(post_id: post.id, id: comment.id), remote: true, method: :delete, title: 'Delete Comment', class: 'cmt-del-btn glyphicon glyphicon-remove', data: { title: "Are you sure?", confirm: "Your comment will be deleted. This cannot be undone." } %>
    <% end %>
    <br> 
  </span> 
<% end %>

<% if user_signed_in? %>
  <hr>
  <%= simple_form_for PostComment.new, url: post_post_comments_path(post), remote: true, method: :post do |f| %>
    <%= f.input :text, as: :string, label: 'Comment', placeholder: 'Add a comment...' %>
    <%= f.submit 'Post', class: 'btn btn-primary btn-block' %>
  <% end %>
<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>
<%= simple_form_for @post do |f| %>
  <%= f.input :photo %>
  <%= f.input :description %>
  <%= f.submit 'Update', class: 'btn btn-success btn-block' %>
<% end %>

app/views/posts/index.html.erb
<div class="col-md-10 col-md-offset-1">
	<div id="my-posts">
	  <%= render @posts %>
	</div><!-- my posts id -->

	<div class = "text-center" id="infinite-scrolling">
    <%= will_paginate @posts %>
	</div>
</div>

app/views/posts/index.js.erb
// for infinite load
$('#my-posts').append('<%= j render @posts %>');
<% if @posts.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate @posts %>');
<% else %>
  $(window).off('scroll');
  $('.pagination').remove();
<% end %>

app/views/posts/new.html.erb
<%= simple_form_for @post do |f| %>
  <div id="pictureInput">
  	<%= f.input :photo, required: true %>
  </div>

  <div id="target"></div>
  
  <%= f.input :description %>
  <%= f.submit 'Post', class: 'btn btn-success btn-block' %>
<% end %>

<!-- This is needed for image preview -->
<script type="text/javascript">
	$(function() {
	  $('#pictureInput').on('change', function(event) {
	    var files = event.target.files;
	    var image = files[0]
	    var reader = new FileReader();
	    reader.onload = function(file) {
	      var img = new Image();
	      console.log(file);
	      img.src = file.target.result;
	      $('#target').html(img);
	    }
	    reader.readAsDataURL(image);
	    console.log(files);
	  });
	});
</script>

app/views/posts/show.html.erb
<div class="post_box">

  <div class="post_header">
    <%= link_to (cl_image_tag @post.user_photo, :secure => true), user_path(@post.user_id), class: 'prof_pic_small' %>
    <%= link_to @post.user_name, user_path(@post.user_id) %>
    <span class="timestamp pull-right"><%= distance_of_time_in_words(DateTime.now, @post.created_at) %> ago</span>
  </div>

  <%= cl_image_tag @post.photo, :secure => true, class: 'photo' %>

  <div class="post_body row">
    <span id="likes_container_<%= @post.id %>">
      <%= render partial: 'likes', locals: {post: @post} %>
    </span>
    <%= @post.description %>

    <br /><br />

    <% if @post.user == current_user %>
      <%= link_to 'Edit Post', edit_post_path(@post.id), class: 'btn btn-warning btn-sm' %>
      <%= link_to 'Delete Post', post_path(@post.id), method: :delete, class: 'btn btn-danger btn-sm', data: { title: "Are you sure?", confirm: "Your post will be deleted. This cannot be undone." } %>
    <% end %>
  </div>

  <span id="post_comments_container_<%= @post.id %>">
    <%= render partial: 'post_comments', locals: {post: @post} %>
  </span>

</div>